if(NOT ZLIB_PACKAGE_DIR)
	message("ERROR: ZLIB_PACKAGE_DIR requires to be set")
endif(NOT ZLIB_PACKAGE_DIR)

set(GLI_INCLUDE_DIR ${ZLIB_PACKAGE_DIR})
set(GLI_LIBRARY_DIR )

include_directories(${GLI_INCLUDE_DIR})

if(ZLIB_PACKAGE_DIR AND GLI_INCLUDE_DIR)
	set(GLI_FOUND "YES")
endif(ZLIB_PACKAGE_DIR AND GLI_INCLUDE_DIR)
