#pragma once

#include <cstdint>

// AUTOGENERATED FILE - DO NOT EDIT
// See contrib/dbmeta.py
namespace wowgm::game::datastores
{
    namespace DataStores {
        void Initialize();

        template <typename T> T const* GetRecord(std::uint32_t index);
    }
}

