#pragma once

#include "DBC.hpp"

#include <cstddef>
#include <type_traits>
#include <cstdint>

// AUTOGENERATED FILE - DO NOT EDIT
// See contrib/dbmeta.py
namespace wowgm::game::datastores
{
#pragma pack(push, 1)
    struct Startup_StringsEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemSparseEntry {
        uint32_t ID;
        uint32_t Quality;
        uint32_t Flags[2];
        float UnkMember3;
        float UnkMember4;
        uint32_t BuyCount;
        uint32_t BuyPrice;
        uint32_t SpellPrice;
        uint32_t InventoryType;
        uint32_t AllowableClass;
        uint32_t AllowableRace;
        uint32_t ItemLevel;
        struct {
            uint32_t Level;
            uint32_t Skill;
            uint32_t SkillRank;
            uint32_t Spell;
            uint32_t HonorRank;
            uint32_t CityRank;
            struct {
                uint32_t FactionID;
                uint32_t Rank;
            } Reputation;
        } Requirements;
        uint32_t MaxCount;
        uint32_t Stackable;
        uint32_t ContainerSlots;
        struct {
            uint32_t Type[10];
            uint32_t Value[10];
            uint32_t Allocation[10];
            uint32_t Multiplier[10];
        } Stats;
        uint32_t ScalingStatDistributionID;
        uint32_t DamageType;
        uint32_t Delay;
        float RangedModifier;
        uint32_t SpellID[5];
        uint32_t SpellTriggerMode[5];
        uint32_t SpellCharges[5];
        uint32_t SpellCooldowns[5];
        uint32_t SpellCategories[5];
        uint32_t SpellCategoriesCooldowns[5];
        uint32_t Bonding;
        const char* Name[4];
        const char* Description;
        uint32_t PageText;
        uint32_t LanguageID;
        uint32_t PageMaterialID;
        uint32_t StartsQuest;
        uint32_t LockID;
        uint32_t Material;
        uint32_t Sheath;
        uint32_t RandomProperty;
        uint32_t RandomSuffix;
        uint32_t ItemSetID;
        uint32_t AreaID;
        uint32_t MapID;
        uint32_t BagFamily;
        uint32_t TotemCategory;
        uint32_t Color[3];
        uint32_t Content[3];
        uint32_t SocketBonus;
        uint32_t GemProperties;
        float ArmorDamageModifier;
        uint32_t Duration;
        uint32_t ItemLimitCategoryID;
        uint32_t HolidayID;
        float ScalingStatFactor;
        uint32_t CurrencySubstitutionID;
        uint32_t CurrencySubstitutionCount;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellVisualKitEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12[3];
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        uint32_t UnkMember15;
        uint32_t UnkMember16[4];
        float UnkMember17[4];
        float UnkMember18[4];
        float UnkMember19[4];
        float UnkMember20[4];
        uint32_t UnkMember21;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellVisualEffectNameEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
        float UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        uint32_t UnkMember7;
        float UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellEffectEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        float UnkMember6;
        float UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12[2];
        float UnkMember13;
        uint32_t UnkMember14[2];
        float UnkMember15;
        uint32_t UnkMember16[3];
        uint32_t UnkMember17;
        uint32_t UnkMember18[2];
        uint32_t UnkMember19;
        uint32_t UnkMember20;
        uint32_t UnkMember21;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ParticleColorEntry {
        uint32_t ID;
        uint32_t UnkMember1[3];
        uint32_t UnkMember2[3];
        uint32_t UnkMember3[3];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ObjectEffectPackageElemEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ObjectEffectPackageEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ObjectEffectModifierEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ObjectEffectGroupEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ObjectEffectEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        float UnkMember8[3];
        uint32_t UnkMember9;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct NameGenEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LoadingScreensEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemVisualEffectsEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemVisualsEntry {
        uint32_t ID;
        uint32_t UnkMember1[5];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDisplayInfoEntry {
        uint32_t ID;
        const char* UnkMember1[2];
        const char* UnkMember2[2];
        const char* UnkMember3[2];
        uint32_t UnkMember4[3];
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8[2];
        const char* UnkMember9[8];
        uint32_t UnkMember10;
        uint32_t UnkMember11;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct HelmetGeosetVisDataEntry {
        uint32_t ID;
        uint32_t UnkMember1[7];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GuildColorEmblemEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GuildColorBorderEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GuildColorBackgroundEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GlueScreenEmoteEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GameTipsEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureModelDataEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        float UnkMember7;
        float UnkMember8;
        float UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        float UnkMember14;
        float UnkMember15;
        float UnkMember16;
        float UnkMember17[3];
        float UnkMember18[3];
        float UnkMember19;
        float UnkMember20;
        float UnkMember21;
        float UnkMember22;
        float UnkMember23;
        float UnkMember24;
        float UnkMember25;
        float UnkMember26;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureFamilyEntry {
        uint32_t ID;
        float UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5[2];
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        const char* UnkMember9;
        const char* UnkMember10;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureDisplayInfoExtraEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8[11];
        uint32_t UnkMember9;
        const char* UnkMember10;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureDisplayInfoEntry {
        uint32_t ID;
        uint32_t ModelID;
        uint32_t SoundID;
        uint32_t ExtendedDisplayInfoID;
        float ModelScale;
        uint32_t ModelAlpha;
        const char* TextureVariations[3];
        const char* PortraitTextureName;
        uint32_t SizeClass;
        uint32_t BloodID;
        uint32_t CreatureSoundID;
        uint32_t ParticleColorID;
        uint32_t CreatureGeosetData;
        uint32_t ObjectEffectPackageID;
        uint32_t AnimReplacementSetID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CharStartOutfitEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5[24];
        uint32_t UnkMember6[24];
        uint32_t UnkMember7[24];
        uint32_t UnkMember8;
        uint32_t UnkMember9;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimReplacementSetEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimReplacementEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimKitSegmentEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        float UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        uint32_t UnkMember15;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimKitPriorityEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundProviderPreferencesEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        float UnkMember9;
        uint32_t UnkMember10;
        float UnkMember11;
        uint32_t UnkMember12;
        float UnkMember13;
        float UnkMember14;
        float UnkMember15;
        uint32_t UnkMember16;
        float UnkMember17;
        float UnkMember18;
        float UnkMember19;
        float UnkMember20;
        float UnkMember21;
        float UnkMember22;
        float UnkMember23;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpamMessagesEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundFilterElemEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4[9];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundFilterEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ResistancesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct NamesReservedEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct NamesProfanityEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MovieVariationEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MovieFileDataEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MovieEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemSubClassEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        const char* UnkMember10;
        const char* UnkMember11;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemClassEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3;
        const char* UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct FileDataEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct FactionTemplateEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6[4];
        uint32_t UnkMember7[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct FactionGroupEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ChrRacesEntry {
        uint32_t ID;
        uint32_t Flags;
        uint32_t FactionID;
        uint32_t ExplorationSoundID;
        uint32_t MaleDisplayID;
        uint32_t FemaleDisplayID;
        const char* ClientPrefix;
        uint32_t BaseLanguageID;
        uint32_t CreatureType;
        uint32_t ResSicknessSpellID;
        uint32_t SplashSoundID;
        const char* ClientFileString;
        uint32_t CinematicSequenceID;
        uint32_t Alliance;
        const char* Name;
        const char* GenderNames[2];
        const char* FacialHairCustomization[2];
        const char* HairCustomization;
        uint32_t UnkMember19;
        uint32_t UnkMember20;
        uint32_t UnkMember21;
        uint32_t UnkMember22;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ChrClassesEntry {
        uint32_t ID;
        uint32_t PowerDisplayID;
        const char* PetNameIdentifier;
        const char* Name;
        const char* GenderNames[2];
        const char* FileName;
        uint32_t SpellClassSet;
        uint32_t Flags;
        uint32_t CinematicSequence;
        uint32_t Expansion;
        uint32_t AttackPowerPerStrength;
        uint32_t AttackPowerPerAgility;
        uint32_t RangedAttackPowerPerAgility;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ChatProfanityEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CharacterFacialHairStylesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3[5];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CharSectionsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        const char* UnkMember4[3];
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CharHairGeosetsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CharBaseInfoEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct Cfg_ConfigsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct Cfg_CategoriesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        const char* UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct BannedAddOnsEntry {
        uint32_t ID;
        uint32_t UnkMember1[4];
        uint32_t UnkMember2[4];
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimKitConfigBoneSetEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimKitConfigEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimKitEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimKitBoneSetEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimKitBoneSetAliasEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PhaseShiftZoneSoundsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WorldChunkSoundsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WorldStateZoneSoundsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ZoneMusicEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2[2];
        uint32_t UnkMember3[2];
        uint32_t UnkMember4[2];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ZoneIntroMusicTableEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WorldStateUIEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        const char* UnkMember6;
        const char* UnkMember7;
        const char* UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        const char* UnkMember11;
        const char* UnkMember12;
        const char* UnkMember13;
        uint32_t UnkMember14[3];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WorldSafeLocsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2[3];
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WorldMapTransformsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2[2];
        float UnkMember3[2];
        uint32_t UnkMember4;
        float UnkMember5[2];
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WorldMapOverlayEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2[4];
        const char* UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WorldMapContinentEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        float UnkMember6[2];
        float UnkMember7;
        float UnkMember8[2];
        float UnkMember9[2];
        uint32_t UnkMember10;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WorldMapAreaEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        float UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WeaponSwingSounds2Entry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WeaponImpactSoundsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3[10];
        uint32_t UnkMember4[10];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct World_PVP_AreaEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct VocalUISoundsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3[2];
        uint32_t UnkMember4[2];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct VehicleUIIndSeatEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3;
        float UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct VehicleUIIndicatorEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct VehicleSeatEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3[3];
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        float UnkMember7;
        float UnkMember8;
        float UnkMember9;
        float UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        uint32_t UnkMember15;
        uint32_t UnkMember16;
        float UnkMember17;
        float UnkMember18;
        float UnkMember19;
        float UnkMember20;
        float UnkMember21;
        float UnkMember22;
        float UnkMember23;
        uint32_t UnkMember24;
        uint32_t UnkMember25;
        uint32_t UnkMember26;
        float UnkMember27;
        float UnkMember28;
        float UnkMember29;
        uint32_t UnkMember30;
        uint32_t UnkMember31;
        uint32_t UnkMember32;
        uint32_t UnkMember33;
        uint32_t UnkMember34;
        uint32_t UnkMember35;
        uint32_t UnkMember36;
        float UnkMember37;
        float UnkMember38;
        uint32_t UnkMember39;
        uint32_t UnkMember40;
        uint32_t UnkMember41;
        uint32_t UnkMember42;
        uint32_t UnkMember43;
        float UnkMember44;
        float UnkMember45;
        float UnkMember46;
        float UnkMember47;
        float UnkMember48[3];
        float UnkMember49;
        float UnkMember50;
        float UnkMember51;
        float UnkMember52;
        float UnkMember53;
        uint32_t UnkMember54;
        uint32_t UnkMember55;
        uint32_t UnkMember56;
        uint32_t UnkMember57;
        uint32_t UnkMember58;
        uint32_t UnkMember59;
        uint32_t UnkMember60;
        uint32_t UnkMember61;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct VehicleEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
        float UnkMember5;
        uint32_t UnkMember6[8];
        float UnkMember7;
        float UnkMember8;
        float UnkMember9;
        float UnkMember10;
        float UnkMember11;
        float UnkMember12;
        float UnkMember13;
        float UnkMember14;
        float UnkMember15;
        float UnkMember16;
        float UnkMember17;
        float UnkMember18;
        float UnkMember19;
        float UnkMember20[2];
        const char* UnkMember21;
        const char* UnkMember22;
        const char* UnkMember23[2];
        float UnkMember24;
        uint32_t UnkMember25;
        float UnkMember26;
        uint32_t UnkMember27;
        uint32_t UnkMember28[3];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct UnitPowerBarEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        float UnkMember5;
        float UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8[6];
        uint32_t UnkMember9[6];
        uint32_t UnkMember10;
        const char* UnkMember11;
        const char* UnkMember12;
        const char* UnkMember13;
        const char* UnkMember14;
        float UnkMember15;
        float UnkMember16;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct UnitBloodEntry {
        uint32_t ID;
        uint32_t UnkMember1[2];
        uint32_t UnkMember2[2];
        const char* UnkMember3[5];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct UnitBloodLevelsEntry {
        uint32_t ID;
        uint32_t UnkMember1[3];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TransportRotationEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TransportPhysicsEntry {
        uint32_t ID;
        float UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        float UnkMember7;
        float UnkMember8;
        float UnkMember9;
        float UnkMember10;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TransportAnimationEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3[3];
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TotemCategoryEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TerrainTypeSoundsEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TaxiPathEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TaxiPathNodeEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4[3];
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TaxiNodesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2[3];
        const char* UnkMember3;
        uint32_t UnkMember4[2];
        uint32_t UnkMember5;
        float UnkMember6[2];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TalentTreePrimarySpellsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TalentTabEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        const char* UnkMember6;
        const char* UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9[2];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TalentEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4[5];
        uint32_t UnkMember5[3];
        uint32_t UnkMember6[3];
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9[2];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SummonPropertiesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct StringLookupsEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct StationeryEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellVisualKitModelAttachEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4[3];
        float UnkMember5;
        float UnkMember6;
        float UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellVisualKitAreaModelEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellVisualEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        uint32_t UnkMember15;
        uint32_t UnkMember16;
        uint32_t UnkMember17;
        uint32_t UnkMember18;
        uint32_t UnkMember19;
        uint32_t UnkMember20;
        uint32_t UnkMember21;
        uint32_t UnkMember22;
        uint32_t UnkMember23;
        uint32_t UnkMember24;
        uint32_t UnkMember25;
        float UnkMember26[3];
        float UnkMember27[3];
        uint32_t UnkMember28;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellTotemsEntry {
        uint32_t ID;
        uint32_t UnkMember1[2];
        uint32_t UnkMember2[2];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellTargetRestrictionsEntry {
        uint32_t ID;
        float ConeAngle;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellSpecialUnitEffectEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellShapeshiftFormEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7[4];
        uint32_t UnkMember8[8];
        uint32_t UnkMember9;
        uint32_t UnkMember10;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellShapeshiftEntry {
        uint32_t ID;
        uint32_t UnkMember1[2];
        uint32_t UnkMember2[2];
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellScalingEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        float UnkMember5[3];
        float UnkMember6[3];
        float UnkMember7[3];
        float UnkMember8;
        uint32_t UnkMember9;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellRuneCostEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellReagentsEntry {
        uint32_t ID;
        uint32_t UnkMember1[8];
        uint32_t UnkMember2[8];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellPowerEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        float UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellRangeEntry {
        uint32_t ID;
        float UnkMember1[2];
        float UnkMember2[2];
        uint32_t UnkMember3;
        const char* UnkMember4;
        const char* UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellRadiusEntry {
        uint32_t ID;
        float UnkMember1;
        float UnkMember2;
        float UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellMissileMotionEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellMissileEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        float UnkMember7;
        float UnkMember8;
        float UnkMember9;
        float UnkMember10;
        float UnkMember11;
        float UnkMember12;
        float UnkMember13;
        float UnkMember14;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellMechanicEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellLevelsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellItemEnchantmentConditionEntry {
        uint32_t ID;
        uint32_t UnkMember1[1];
        uint32_t UnkMember2[5];
        uint32_t UnkMember3[1];
        uint32_t UnkMember4[1];
        uint32_t UnkMember5[5];
        uint32_t UnkMember6[1];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellItemEnchantmentEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2[3];
        uint32_t UnkMember3[3];
        uint32_t UnkMember4[3];
        uint32_t UnkMember5[3];
        const char* UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellInterruptsEntry {
        uint32_t ID;
        uint32_t UnkMember1[2];
        uint32_t UnkMember2[2];
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellIconEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellFocusObjectEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellFlyoutItemEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellFlyoutEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        const char* UnkMember5;
        const char* UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellEquippedItemsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellEffectCameraShakesEntry {
        uint32_t ID;
        uint32_t UnkMember1[3];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellDurationEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellDispelTypeEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        const char* UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellDifficultyEntry {
        uint32_t ID;
        uint32_t UnkMember1[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellDescriptionVariablesEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellEntry {
        uint32_t ID;
        uint32_t Attributes[11];
        uint32_t SpellCastingTimeID;
        uint32_t SpellDurationID;
        uint32_t PowerType;
        uint32_t SpellRangeID;
        float Speed;
        uint32_t SpellVisualID[2];
        uint32_t SpellIconID;
        uint32_t ActiveIconID;
        const char* Name;
        const char* Rank;
        const char* Description;
        const char* Tooltip;
        uint32_t SchoolMask;
        uint32_t SpellRuneCostID;
        uint32_t SpellMissileID;
        uint32_t SpellDescriptionVariableID;
        uint32_t SpellDifficultyID;
        float AttackPowerCoefficient;
        uint32_t SpellScalingID;
        uint32_t SpellAuraOptionsID;
        uint32_t SpellAuraRestrictionsID;
        uint32_t SpellCastingRequirementsID;
        uint32_t SpellCategoriesID;
        uint32_t SpellClassOptionsID;
        uint32_t SpellCooldownsID;
        uint32_t UnkMember37;
        uint32_t SpellEquippedItemsID;
        uint32_t SpellInterruptsID;
        uint32_t SpellLevelsID;
        uint32_t SpellPowerID;
        uint32_t SpellReagentsID;
        uint32_t SpellShapeshiftID;
        uint32_t SpellTargetRestrictionsID;
        uint32_t SpellTotemsID;
        uint32_t ResearchProject;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellCooldownsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellClassOptionsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2[3];
        uint32_t UnkMember3;
        const char* UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellChainEffectsEntry {
        uint32_t ID;
        float UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        const char* UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        float UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        float UnkMember13;
        float UnkMember14;
        float UnkMember15;
        float UnkMember16;
        float UnkMember17;
        float UnkMember18;
        float UnkMember19;
        float UnkMember20;
        float UnkMember21;
        float UnkMember22;
        float UnkMember23;
        float UnkMember24;
        float UnkMember25;
        float UnkMember26;
        float UnkMember27;
        float UnkMember28;
        float UnkMember29;
        float UnkMember30;
        float UnkMember31;
        float UnkMember32;
        float UnkMember33;
        float UnkMember34;
        float UnkMember35;
        float UnkMember36;
        float UnkMember37;
        float UnkMember38;
        uint32_t UnkMember39;
        uint32_t UnkMember40;
        uint32_t UnkMember41;
        uint32_t UnkMember42;
        uint32_t UnkMember43;
        const char* UnkMember44;
        uint32_t UnkMember45;
        float UnkMember46;
        float UnkMember47;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellCategoryEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellCategoriesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellCastTimesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellCastingRequirementsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellAuraVisXTalentTabEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellAuraVisibilityEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellAuraRestrictionsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellAuraOptionsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SpellActivationOverlayEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        float UnkMember5;
        uint32_t UnkMember6[3];
        uint32_t UnkMember7;
        uint32_t UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundAmbienceFlavorEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundAmbienceEntry {
        uint32_t ID;
        uint32_t UnkMember1[2];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SkillTiersEntry {
        uint32_t ID;
        uint32_t UnkMember1[16];
        uint32_t UnkMember2[16];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SkillRaceClassInfoEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SkillLineEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        const char* UnkMember3;
        uint32_t UnkMember4;
        const char* UnkMember5;
        uint32_t UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SkillLineCategoryEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SkillLineAbilitySortedSpellEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SkillLineAbilityEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ServerMessagesEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ScreenLocationEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ScreenEffectEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3[4];
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ScalingStatValuesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14[4];
        uint32_t UnkMember15[4];
        uint32_t UnkMember16[4];
        uint32_t UnkMember17[4];
        uint32_t UnkMember18[4];
        uint32_t UnkMember19[4];
        uint32_t UnkMember20[4];
        uint32_t UnkMember21[4];
        uint32_t UnkMember22;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ScalingStatDistributionEntry {
        uint32_t ID;
        uint32_t UnkMember1[10];
        uint32_t UnkMember2[10];
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct RandPropPointsEntry {
        uint32_t ID;
        uint32_t UnkMember1[5];
        uint32_t UnkMember2[5];
        uint32_t UnkMember3[5];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ResearchSiteEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ResearchProjectEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        const char* UnkMember7;
        uint32_t UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ResearchFieldEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ResearchBranchEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        const char* UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct QuestXPEntry {
        uint32_t ID;
        uint32_t UnkMember1[10];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct QuestSortEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct QuestPOIPointEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct QuestPOIBlobEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct QuestInfoEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct QuestFactionRewardEntry {
        uint32_t ID;
        uint32_t UnkMember1[10];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PvpDifficultyEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PowerDisplayEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PlayerConditionEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PhaseXPhaseGroupEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PhaseEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PaperDollItemFrameEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PageTextMaterialEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct PackageEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct OverrideSpellDataEntry {
        uint32_t ID;
        uint32_t UnkMember1[10];
        uint32_t UnkMember2;
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct NumTalentsAtLevelEntry {
        uint32_t ID;
        float UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct NPCSoundsEntry {
        uint32_t ID;
        uint32_t UnkMember1[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MountTypeEntry {
        uint32_t ID;
        uint32_t UnkMember1[24];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MountCapabilityEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MaterialEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MapDifficultyEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        const char* UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MailTemplateEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LockTypeEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
        const char* UnkMember3;
        const char* UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LockEntry {
        uint32_t ID;
        uint32_t UnkMember1[8];
        uint32_t UnkMember2[8];
        uint32_t UnkMember3[8];
        uint32_t UnkMember4[8];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LoadingScreenTaxiSplinesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2[8];
        float UnkMember3[8];
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LfgDungeonsEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        const char* UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        uint32_t UnkMember15;
        const char* UnkMember16;
        uint32_t UnkMember17;
        uint32_t UnkMember18;
        uint32_t UnkMember19;
        uint32_t UnkMember20;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LfgDungeonsGroupingMapEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LfgDungeonGroupEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LfgDungeonExpansionEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LanguagesEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LanguageWordsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct JournalInstanceEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        const char* UnkMember7;
        const char* UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct JournalEncounterSectionEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        const char* UnkMember9;
        const char* UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct JournalEncounterEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3[2];
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        const char* UnkMember8;
        const char* UnkMember9;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct JournalEncounterItemEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct JournalEncounterCreatureEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        const char* UnkMember5;
        const char* UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemSubClassMaskEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemSetEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2[17];
        uint32_t UnkMember3[8];
        uint32_t UnkMember4[8];
        uint32_t UnkMember5;
        uint32_t UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemReforgeEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemRandomSuffixEntry {
        uint32_t ID;
        const char* UnkMember1;
        const char* UnkMember2;
        uint32_t UnkMember3[5];
        uint32_t UnkMember4[5];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemRandomPropertiesEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2[5];
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemPurchaseGroupEntry {
        uint32_t ID;
        uint32_t UnkMember1[8];
        const char* UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemPriceBaseEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        float UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemPetFoodEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemNameDescriptionEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemLimitCategoryEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemGroupSoundsEntry {
        uint32_t ID;
        uint32_t UnkMember1[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDisenchantLootEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDamageWandEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDamageTwoHandCasterEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDamageTwoHandEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDamageThrownEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDamageRangedEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDamageOneHandCasterEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDamageOneHandEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemDamageAmmoEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemBagFamilyEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemArmorShieldEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2[7];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemArmorTotalEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
        float UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemArmorQualityEntry {
        uint32_t ID;
        float UnkMember1[7];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ImportPriceWeaponEntry {
        uint32_t ID;
        float UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ImportPriceShieldEntry {
        uint32_t ID;
        float UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ImportPriceQualityEntry {
        uint32_t ID;
        float UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ImportPriceArmorEntry {
        uint32_t ID;
        float UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct HolidaysEntry {
        uint32_t ID;
        uint32_t UnkMember1[10];
        uint32_t UnkMember2[26];
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5[10];
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        const char* UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct HolidayNamesEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct HolidayDescriptionsEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GuildPerkSpellsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtSpellScalingEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtRegenMPPerSptEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtOCTRegenMPEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtOCTHpPerStaminaEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtOCTClassCombatRatingScalarEntry {
        uint32_t ID;
        float UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtOCTBaseMPByClassEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtOCTBaseHPByClassEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtNPCManaCostScalerEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtChanceToSpellCritBaseEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtChanceToSpellCritEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtChanceToMeleeCritBaseEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtChanceToMeleeCritEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtCombatRatingsEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct gtBarberShopCostBaseEntry {
        uint32_t ID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GMTicketCategoryEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GMSurveySurveysEntry {
        uint32_t ID;
        uint32_t UnkMember1[15];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GMSurveyQuestionsEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GMSurveyCurrentSurveyEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GMSurveyAnswersEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GlyphSlotEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GlyphPropertiesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GemPropertiesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GameTablesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GameObjectDisplayInfoEntry {
        uint32_t ID;
        const char* FileName;
        uint32_t SoundID[10];
        float Minimum[3];
        float Maximum[3];
        uint32_t TransportID;
        float OverrideLootEffectScale;
        float OverrideNameScale;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GameObjectArtKitEntry {
        uint32_t ID;
        const char* UnkMember1[3];
        const char* UnkMember2[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct FootstepTerrainLookupEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct FactionEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2[4];
        uint32_t UnkMember3[4];
        uint32_t UnkMember4[4];
        uint32_t UnkMember5[4];
        uint32_t UnkMember6;
        float UnkMember7[2];
        uint32_t UnkMember8[2];
        const char* UnkMember9;
        const char* UnkMember10;
        uint32_t UnkMember11;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ExhaustionEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
        const char* UnkMember5;
        float UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct EnvironmentalDamageEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct EmotesTextEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3[16];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct EmotesTextSoundEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct EmotesTextDataEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct EmotesEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DurabilityQualityEntry {
        uint32_t ID;
        float UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DurabilityCostsEntry {
        uint32_t ID;
        uint32_t UnkMember1[21];
        uint32_t UnkMember2[8];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DungeonMapChunkEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DungeonMapEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3[2];
        float UnkMember4[2];
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DungeonEncounterEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        const char* UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DestructibleModelDataEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        uint32_t UnkMember15;
        uint32_t UnkMember16;
        uint32_t UnkMember17;
        uint32_t UnkMember18;
        uint32_t UnkMember19;
        uint32_t UnkMember20;
        uint32_t UnkMember21;
        uint32_t UnkMember22;
        uint32_t UnkMember23;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DeathThudLookupsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DanceMovesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        const char* UnkMember5;
        const char* UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CurrencyCategoryEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CurrencyTypesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        const char* UnkMember3[2];
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        const char* UnkMember9;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureTypeEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureSpellDataEntry {
        uint32_t ID;
        uint32_t UnkMember1[4];
        uint32_t UnkMember2[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureSoundDataEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14[5];
        uint32_t UnkMember15[4];
        uint32_t UnkMember16;
        uint32_t UnkMember17;
        uint32_t UnkMember18;
        uint32_t UnkMember19;
        uint32_t UnkMember20;
        uint32_t UnkMember21;
        uint32_t UnkMember22;
        uint32_t UnkMember23;
        float UnkMember24;
        float UnkMember25;
        uint32_t UnkMember26;
        uint32_t UnkMember27;
        uint32_t UnkMember28;
        uint32_t UnkMember29;
        uint32_t UnkMember30;
        uint32_t UnkMember31;
        uint32_t UnkMember32;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureMovementInfoEntry {
        uint32_t ID;
        float UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CreatureImmunitiesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6[6];
        uint32_t UnkMember7;
        uint32_t UnkMember8[12];
        uint32_t UnkMember9;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CinematicSequencesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2[8];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CinematicCameraEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3[3];
        float UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ChrClassesXPowerTypesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ChatChannelsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
        const char* UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CharTitlesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        const char* UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CastableRaidBuffsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CameraShakesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        float UnkMember7;
        uint32_t UnkMember8;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct CameraModeEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4[3];
        float UnkMember5[3];
        float UnkMember6;
        float UnkMember7;
        float UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct BattlemasterListEntry {
        uint32_t ID;
        uint32_t UnkMember1[8];
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        const char* UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct BarberShopStyleEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        const char* UnkMember3;
        float UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct BankBagSlotPricesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AuctionHouseEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        const char* UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ArmorLocationEntry {
        uint32_t ID;
        float UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
        float UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AreaTriggerEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2[3];
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        float UnkMember6;
        float UnkMember7;
        float UnkMember8;
        float UnkMember9;
        float UnkMember10;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AreaAssignmentEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AreaPOISortedWorldStateEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AreaPOIEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2[9];
        uint32_t UnkMember3;
        float UnkMember4[2];
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        const char* UnkMember8;
        const char* UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AreaGroupEntry {
        uint32_t ID;
        uint32_t UnkMember1[6];
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct Achievement_CategoryEntry {
        uint32_t ID;
        int32_t ParentCategoryID;
        const char* Name;
        uint32_t SortOrder;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct Achievement_CriteriaEntry {
        uint32_t ID;
        uint32_t AchievementID;
        uint32_t Type;
        uint32_t MainRequirement;
        uint64_t MainRequirementCount;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        const char* Name;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        uint32_t UnkMember15;
        uint32_t UnkMember16;
        uint32_t UnkMember17[3];
        uint32_t UnkMember18[3];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AchievementEntry {
        uint32_t ID;
        uint32_t RequiredFaction;
        uint32_t MapID;
        int32_t ParentAchievementID;
        const char* Name;
        const char* Description;
        uint32_t CategoryID;
        uint32_t Points;
        uint32_t OrderInCategory;
        uint32_t Flags;
        uint32_t IconID;
        const char* Rewards;
        uint32_t Count;
        uint32_t ReferenceAchievement;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemCurrencyCostEntry {
        uint32_t ID;
        uint32_t UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ItemExtendedCostEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4[5];
        uint32_t UnkMember5[5];
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8[5];
        uint32_t UnkMember9[5];
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct KeyChainEntry {
        uint32_t ID;
        uint8_t UnkMember1[32];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DeclinedWordCasesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct DeclinedWordEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ZoneLightPointEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2[2];
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct ZoneLightEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WMOAreaTableEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        const char* UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct WeatherEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        float UnkMember3;
        float UnkMember4[3];
        const char* UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TerrainTypeEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct TerrainMaterialEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        const char* UnkMember3;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundEntriesFallbacksEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundEmittersEntry {
        uint32_t ID;
        float UnkMember1[3];
        float UnkMember2[3];
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        const char* UnkMember5;
        uint32_t UnkMember6;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundEmitterPillPointsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2[3];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LiquidTypeEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        float UnkMember6;
        float UnkMember7;
        float UnkMember8;
        float UnkMember9;
        uint32_t UnkMember10;
        float UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        const char* UnkMember15[6];
        uint32_t UnkMember16[2];
        float UnkMember17[18];
        uint32_t UnkMember18[4];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LiquidObjectEntry {
        uint32_t ID;
        float UnkMember1;
        float UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LiquidMaterialEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LightSkyboxEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LightFloatBandEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2[16];
        float UnkMember3[16];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LightEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        float UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        uint32_t UnkMember7[8];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GroundEffectTextureEntry {
        uint32_t ID;
        uint32_t UnkMember1[4];
        uint32_t UnkMember2[4];
        uint32_t UnkMember3;
        uint32_t UnkMember4;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct GroundEffectDoodadEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct FootprintTexturesEntry {
        uint32_t ID;
        const char* UnkMember1;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct MapEntry {
        uint32_t ID;
        const char* Directory;
        uint32_t InstanceType;
        uint32_t Flags;
        uint32_t MapType;
        uint32_t IsPvpMap;
        const char* Name;
        uint32_t AreaID;
        const char* Introductions[2];
        uint32_t LoadingScreenID;
        float BattlefieldMapIconScale;
        struct {
            int32_t MapID;
            float X;
            float Y;
        } CorpseInfo;
        int32_t TimeOfDayOverride;
        uint32_t Expansion;
        uint32_t ExpireTime;
        uint32_t MaxPlayers;
        int32_t RootPhaseMapID;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LightParamsEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        float UnkMember4;
        float UnkMember5;
        float UnkMember6;
        float UnkMember7;
        float UnkMember8;
        uint32_t UnkMember9;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct LightIntBandEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2[16];
        uint32_t UnkMember3[16];
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AreaTableEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        const char* UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13[4];
        float UnkMember14;
        float UnkMember15;
        uint32_t UnkMember16;
        uint32_t UnkMember17;
        uint32_t UnkMember18;
        uint32_t UnkMember19;
        uint32_t UnkMember20;
        uint32_t UnkMember21;
        uint32_t UnkMember22;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct AnimationDataEntry {
        uint32_t ID;
        const char* UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundEntriesEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        const char* UnkMember2;
        const char* UnkMember3[10];
        uint32_t UnkMember4[10];
        const char* UnkMember5;
        float UnkMember6;
        uint32_t UnkMember7;
        float UnkMember8;
        float UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        float UnkMember12;
        float UnkMember13;
        float UnkMember14;
        float UnkMember15;
        uint32_t UnkMember16;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct SoundEntriesAdvancedEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        float UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        float UnkMember12;
        float UnkMember13;
        float UnkMember14;
        float UnkMember15;
        float UnkMember16;
        uint32_t UnkMember17;
        uint32_t UnkMember18;
        float UnkMember19;
        float UnkMember20;
        float UnkMember21;
        float UnkMember22;
        uint32_t UnkMember23;
        uint32_t UnkMember24;
        float UnkMember25;
    };
#pragma pack(pop)

#pragma pack(push, 1)
    struct VideoHardwareEntry {
        uint32_t ID;
        uint32_t UnkMember1;
        uint32_t UnkMember2;
        uint32_t UnkMember3;
        uint32_t UnkMember4;
        uint32_t UnkMember5;
        uint32_t UnkMember6;
        uint32_t UnkMember7;
        uint32_t UnkMember8;
        uint32_t UnkMember9;
        uint32_t UnkMember10;
        uint32_t UnkMember11;
        uint32_t UnkMember12;
        uint32_t UnkMember13;
        uint32_t UnkMember14;
        uint32_t UnkMember15;
        uint32_t UnkMember16;
        uint32_t UnkMember17;
        const char* UnkMember18;
        const char* UnkMember19;
        uint32_t UnkMember20;
        uint32_t UnkMember21;
        uint32_t UnkMember22;
    };
#pragma pack(pop)
}
